[package]
name = "beta-faulty-deps"
version = "0.1.0"
authors = ["Giacomo Pasini <g.pasini98@gmail.com>"]
edition = "2018"

[dependencies]
error_code = {git = "https://github.com/rust-lang/crater", rev = "f190933e896443e285e3bb6962fb87d7439b8d65"}

