sudo: false
dist: trusty
language: rust
cache: cargo
rust:
  - stable
  - nightly-2018-01-20

env:
  global:
    # Versions known to work with pinned nightly.
    - CLIPPY_VERSION=0.0.180
    - RUSTFMT_VERSION=0.3.6

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - |
    if ! type -p cargo-install-update; then
        cargo install --force cargo-update
    else
        cargo install-update -i cargo-update
    fi
  - |
    if [[  $TRAVIS_RUST_VERSION =~ nightly-* ]]; then
        cargo install-update -i "clippy:$CLIPPY_VERSION"
        cargo install-update -i "rustfmt-nightly:$RUSTFMT_VERSION"
    fi
script:
  - |
    RUSTFLAGS=-Dwarnings cargo build &&
    cargo test
  - |
    [[ ! $TRAVIS_RUST_VERSION =~ nightly-* ]] || RUSTFLAGS=-Dwarnings cargo fmt -- --write-mode diff
  - |
    [[ ! $TRAVIS_RUST_VERSION =~ nightly-* ]] || RUSTFLAGS=-Dwarnings cargo clippy
