sudo: false
dist: trusty
language: rust
cache: cargo
rust:
  - stable
  - nightly-2018-01-20

env:
  global:
    - RUSTFLAGS=-Dwarnings
    # Versions known to work with pinned nightly.
    - CLIPPY_VERSION=0.0.180

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - |
    if ! type -p cargo-install-update; then
        cargo install --force cargo-update
    else
        cargo install-update -i cargo-update
    fi
  - |
    if [[  $TRAVIS_RUST_VERSION =~ nightly-* ]]; then
        rustup component add rustfmt-preview
        cargo install-update -i "clippy:$CLIPPY_VERSION"
    fi
script:
  - |
    [[ ! $TRAVIS_RUST_VERSION =~ nightly-* ]] || cargo fmt -- --write-mode diff
  - cargo build && cargo test
  - |
    [[ ! $TRAVIS_RUST_VERSION =~ nightly-* ]] || cargo clippy
