sudo: false
dist: trusty
language: rust
cache: cargo
rust:
  - stable
  - nightly-2017-06-08

env:
  global:
    # Version of clippy known to work with pinned nightly.
    - CLIPPY_VERSION=0.0.138

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - |
    if ! type -p cargo-install-update; then
        cargo install --force cargo-update
    else
        cargo install-update -i cargo-update
    fi
  - |
    if [[  $TRAVIS_RUST_VERSION =~ nightly-* ]]; then
        cargo install-update -i "clippy#$CLIPPY_VERSION"
    fi
  - cargo install-update -i rustfmt
script:
  - |
    RUSTFLAGS=-Dwarnings cargo build &&
    cargo test
  - |
    cargo fmt -- --write-mode diff
  - |
    [[ ! $TRAVIS_RUST_VERSION =~ nightly-* ]] || RUSTFLAGS=-Dwarnings cargo clippy
