sudo: required
dist: trusty

services:
  - docker

language: rust
cache: cargo

env:
  global:
    - RUSTFLAGS=-Dwarnings

matrix:
  include:
    # Lint only on stable
    - env: TASK=lint
      rust: stable

    # Tests on all the channels
    - env: TASK=test
      rust: stable
    - env: TASK=test
      rust: beta
    - env: TASK=test
      rust: nightly

  # Don't block CI if a nightly is faulty
  fast_finish: true
  allow_failures:
    - rust: nightly

before_script: |
  if [[ $TASK = "lint" ]]; then
      rustup component add rustfmt-preview
      rustup component add clippy-preview
      cargo run -- create-lists && cargo run -- check-config
  fi

script: |
  if [[ $TASK = "lint" ]]; then
      cargo fmt -- --check && cargo clippy
  elif [[ $TASK = "test" ]]; then
      cargo build && cargo run -- prepare-local --docker-env mini && cargo test
  fi
