[package]
name = "cargobomb"
version = "0.1.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]

[profile.dev]
opt-level = 0

[dependencies]
arc-cell = "0.1.5"
chrono = "0.3"
clap = "2.11.3"
crates-index = "0.10"
dotenv = "0.10.0"
error-chain = "0.10"
flate2 = "0.2.9"
futures = "0.1.13"
futures-cpupool = "0.1.5"
hyper = { git = "https://github.com/hyperium/hyper.git" }
kernel32-sys = "0.2.2"
lazy_static = "0.2"
libc = "0.2.7"
mime = "0.2.3"
rand = "0.3"
ref_slice = "1.1.1"
reqwest = "0.6"
result = "0.0.1"
route-recognizer = "0.1.12"
rustup-dist = { git = "https://github.com/rust-lang-nursery/rustup.rs", tag="1.3.0" }
scopeguard = "0.3"
semver = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
slog = "2"
slog-scope = "4"
slog-term = "2"
tar = "0.4.0"
tempdir = "0.3.4"
tokio-core = "0.1.7"
tokio-io = "0.1.1"
tokio-process = "0.1.2"
tokio-timer = "0.1.1"
toml = "0.4.1"
url = "1.1"
walkdir = "1.0.7"
winapi = "0.2.8"
