[package]
name = "crater"
version = "0.1.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]

build = "build.rs"

[profile.dev]
opt-level = 0

[dependencies]
base64 = "0.9.0"
bytes = "0.4.9"
chrono = { version = "0.4", features = ["serde"] }
chrono-humanize = "0.0.11"
crates-index = "0.12"
crossbeam-utils = "0.5"
csv = "1.0.2"
dotenv = "0.13"
error-chain = "0.12"
failure = "0.1.3"
flate2 = "1"
futures = "0.1.13"
futures-cpupool = "0.1.5"
http = "0.1.10"
hyper = "0.12.8"
lazy_static = "1.0"
mime = "0.3.1"
minifier = { version = "0.0.19", features = ["html"] }
nix = "0.11.0"
petgraph = "0.4.11"
r2d2 = "0.8.2"
r2d2_sqlite = "0.6.0"
rand = "0.5"
ref_slice = "1.1.1"
regex = "1.0"
reqwest = "0.9"
ring = "0.13"
rusoto_core = "0.34.0"
rusoto_credential = "0.13.0"
rusoto_s3 = "0.34.0"
rusqlite = { version = "0.14.0", features = ["chrono", "functions", "bundled"] }
scopeguard = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_regex = "0.3.0"
slog = "~2.3"
slog-scope = "4"
slog-term = "2"
structopt = "0.2"
structopt-derive = "0.2"
tar = "0.4.0"
tempfile = "3.0.0"
tera = "0.11.7"
tokio-core = "0.1.7"
tokio-io = "0.1.1"
tokio-process = "0.1.2"
tokio-timer = "0.1.1"
toml = "0.4.6"
url = "1.1"
walkdir = "2"
warp = "0.1.9"
winapi = "0.3"

[dev-dependencies]
assert_cmd = "0.10.1"
difference = "2.0.0"
num_cpus = "1.8.0"
predicates = "1.0.0"
