[package]
name = "cargobomb"
version = "0.1.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]

[profile.dev]
opt-level = 1

[dependencies]
clap = "2.11.3"
error-chain = "0.5.0"
tempdir = "0.3.4"
url = "1.1"
walkdir = "0.1.8"
json = "0.10.2"
semver = "0.5.0"
lazy_static = "0.2"
chrono = "0.2.25"
serde = "0.8.17"
serde_json = "0.8.3"
serde_derive = "0.8.17"
flate2 = "0.2.9"
tar = "0.4.0"
toml = "0.2.1"
scopeguard = "0.2.0"
libc = "0.2.7"
