[server]
# The list of GitHub users allowed to interact with the GitHub bot
# You can mix usernames and teams
bot-acl = [
    "rust-lang/infra",
    "rust-lang/release",
    "rust-lang/compiler",
    "rust-lang/libs",
]

[server.labels]
# Remove all labels matching this regex when applying new labels
remove = "^S-"
# Automatically apply the following labels to issues/pull requests
experiment-queued = "S-waiting-on-crater"
experiment-completed = "S-waiting-on-review"


# This section contains the list of tested crates when defining an experiment
# with `--crate-select demo`.

[demo-crates]
crates = ["lazy_static"]
github-repos = ["brson/hello-rs"]


[sandbox]
# Maximum amount of RAM allowed during builds
memory-limit = "1536M"  # 1.5G


# These sections allows to customize how crater treats specific crates/repos
#
# The available options for each crate/repo are:
#  - skip            (bool): ignore this crate/repo
#  - skip-tests      (bool): don't run tests in this crate/repo
#  - quiet           (bool): don't kill after two minutes without output
#  - update-lockfile (bool): update the lockfile even if the crate has one
#  - broken          (bool): treat a Crater error on this crate/repo as a build
#                            failure (typically the crate is broken in an
#                            unusual way and we want to indicate the failure
#                            is 'permissible', while still building it if the
#                            failure is resolved in the future)

# Please add a comment along with each entry explaining the reasons of the
# changes, thanks!

[crates]
# crate_name = { option = true }
actix = { skip-tests = true } # flaky test
afl = { broken = true } # dependency yanked
ai = { skip-tests = true } # may fail due to randomness
alumina = { skip = true } # flaky build
astrup = { slow = true } # build time close to 2 minutes
autograd = { skip-tests = true } # may fail due to randomness
caesarlib = { skip-tests = true } # flaky test
cassandra-sys = { broken = true } # dependency yanked
cc = { skip-tests = true } # flaky test
coinnect = { skip-tests = true } # flaky test
conc = { skip-tests = true } # test timeout
cpp_demangle = { broken = true } # dependency yanked
csv = { skip-tests = true } # flaky test
ctx = { skip-tests = true } # tests depends on timing
diskvec = { skip-tests = true } # flaky test
esprit = { broken = true } # broken Cargo.toml
fe_session = { skip-tests = true } # flaky test
feed = { skip-tests = true } # flaky test
fftw = { slow = true } # build time close to 2 minutes
fine_grained = { skip-tests = true } # flaky tests
fsevent = { broken = true } # dependency yanked
fungtaai = { broken = true } # dependency yanked
gcc = { skip-tests = true } # flaky test
gear = { skip = true } # flaky build
geocode = { skip-tests = true } # depends on network
geogrid = { broken = true } # invalid Cargo.toml
glib = { slow = true } # tests slow to run
glium = { slow = true } # tests build time close to 2 minutes
glium_macros = { broken = true } # broken tarball
google-cloudsearch1 = { broken = true } # broken tarball
google-dataflow1_b4 = { broken = true } # broken tarball
google-deploymentmanager2_beta1 = { broken = true } # broken tarball
google-dfareporting2 = { broken = true } # broken tarball
google-dns1_beta1 = { broken = true } # broken tarball
google-genomics1_beta2 = { broken = true } # broken tarball
hashconsing = { skip-tests = true } # flaky test
he_di_internals = { broken = true } # dependency yanked
hyperdav = { skip-tests = true } # relies on an external service
idx = { skip-tests = true } # depends on filesystem
image-stream = { skip-tests = true } # depends on network
ipc-channel = { slow = true } # tests slow to run
libbreakpad-client-sys = { broken = true } # broken tarball
libfoo-test = { broken = true } # dependency yanked
libfuzzy-sys = { skip = true } # flaky build
loadconf = { skip-tests = true } # flaky test
loaded_dice = { skip-tests = true } # may fail due to randomness
lockless = { skip-tests = true } # test timeout
mccs-caps = { skip-tests = true } # flaky test
median_three_quicksort = { skip-tests = true } # sorting library that sometimes doesn't sort (WTF)
milagro-crypto = { skip-tests = true } # flaky test (segfaults)
minc = { broken = true } # dependency yanked
mish = { skip-tests = true } # flaky test (bad math)
modbus = { skip-tests = true } # flaky test
moonlander-gp = { skip-tests = true } # may fail due to randomness
multihash = { broken = true } # dependency yanked
nanopow-rs = { slow = true } # tests slow to run
net-utils = { skip-tests = true } # depends on network
nexus-rs = { skip-tests = true } # flaky tests
nss-sys = { skip-tests = true } # flaky test (sefaults)
pangocairo = { broken = true } # dependency yanked
pnet = { broken = true } # missing feature
poolite = { skip-tests = true } # flaky test
read-process-memory = { skip-tests = true } # flaky tests
reql = { broken = true } # dependency yanked
reql-io = { broken = true } # dependency yanked
restson = { skip-tests = true } # uses HTTP requests
rpc = { broken = true } # missing Cargo.toml
rspotify = { slow = true } # slow build
ruma-signatures = { broken = true } # dependency yanked
rusoto = { broken = true } # dependency yanked
rustlearn = { skip-tests = true } # non-deterministic
rustysecrets-cli = { broken = true } # dependency yanked
sacn = { skip-tests = true } # "Tests just fail if RUST_TEST_THREADS > 1" -author
scram = { broken = true } # dependency yanked
scroll = { broken = true } # dependency yanked
sgxs = { broken = true } # dependency yanked
signatory-ring = { skip-tests = true } # flaky tests
silk = { slow = true } # tests slow to run
simd = { broken = true } # missing feature
simple-munin-plugin = { skip-tests = true } # flaky test
slotmap = { skip-tests = true } # flaky tests
solana = { skip-tests = true } # flaky tests
structopt = { broken = true } # missing feature
sysconf = { skip-tests = true } # flaky test
tasks-framework = { skip-tests = true } # flaky tests
theban_interval_tree = { skip-tests = true } # flaky tests
tokio = { broken = true } # missing feature
tokio-periodic = { skip-tests = true } # flaky tests
tokio-rustls = { broken = true } # missing feature
tokio-zmq = { broken = true } # missing feature
touch = { skip-tests = true } # depends on the filesystem
treeflection = { skip-tests = true } # flaky test
update_rate = { skip-tests = true } # flaky tests
urdf-viz = { skip = true } # flaky build
vidar = { skip-tests = true } # flaky test
waveform_space = { skip-tests = true } # may fail due to randomness
xoroshiro = { broken = true } # dependency yanked
yup-hyper-mock = { slow = true } # tests slow to run

[github-repos]
# "org_name/repo_name" = { option = true }
"BurntSushi/cargo-benchcmp" = { update-lockfile = true } # outdated lockfile
"KeenS/cargo-pack-docker" = { update-lockfile = true } # outdated lockfile
"adfaure/batsim.rs" = { update-lockfile = true } # outdated lockfile
"anvie/litcrypt.rs" = { broken = true } # path-only dependency
"cardoe/cargo-bitbake" = { update-lockfile = true } # outdated lockfile
"cora32/Linkcrawl" = { update-lockfile = true } # outdated lockfile
"creators/cli.sudoku.rs" = { update-lockfile = true } # outdated lockfile
"djmcgill/form" = { update-lockfile = true } # outdated lockfile
"emabee/rust-hdbconnect" = { update-lockfile = true } # outdated lockfile
"fiirhok/mailcheck.rs" = { update-lockfile = true } # outdated lockfile
"frankier/suchalotofdata" = { update-lockfile = true } # outdated lockfile
"frewsxcv/alert-after" = { update-lockfile = true } # outdated lockfile
"jamii/imp" = { update-lockfile = true } # outdated lockfile
"japaric/swap-ld" = { update-lockfile = true } # outdated lockfile
"jswrenn/beep" = { update-lockfile = true } # outdated lockfile
"max6cn/Kaleidoscope.rs" = { update-lockfile = true } # outdated lockfile
"megamsys/megam_api.rs" = { update-lockfile = true } # outdated lockfile
"mmacedoeu/csvtoredis.rs" = { update-lockfile = true } # outdated lockfile
"olegakbarov/cali" = { update-lockfile = true } # outdated lockfile
"pdpi/synth.rs" = { update-lockfile = true } # outdated lockfile
"rustoscript/js.rs-parser" = { update-lockfile = true } # outdated lockfile
"sozu-proxy/sozu" = { skip-tests = true } # flaky tests
"steveklabnik/rustdoc" = { update-lockfile = true } # outdated lockfile
"ttacon/github.rs" = { update-lockfile = true } # outdated lockfile
"vitiral/artifact" = { broken = true } # path-only dependency
"volks73/cargo-wix" = { skip = true } # flaky test
